// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_1kHT20oCyWJ91rSOSgxYButq8BxTo18',
    appId: '1:688917138939:web:68020c4695b79369114f5e',
    messagingSenderId: '688917138939',
    projectId: 'metro-auth-20cc7',
    authDomain: 'metro-auth-20cc7.firebaseapp.com',
    storageBucket: 'metro-auth-20cc7.appspot.com',
    measurementId: 'G-4YF5CTNDGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmjyt8rtOJ6aHDF55DwlpA1kmxj0NQ8og',
    appId: '1:688917138939:android:3c5c6fc836d15111114f5e',
    messagingSenderId: '688917138939',
    projectId: 'metro-auth-20cc7',
    storageBucket: 'metro-auth-20cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnvGTChUJe3w3O4UYpKt7wRV6MnHCl_wA',
    appId: '1:688917138939:ios:6e4473c3a63b5ce3114f5e',
    messagingSenderId: '688917138939',
    projectId: 'metro-auth-20cc7',
    storageBucket: 'metro-auth-20cc7.appspot.com',
    iosBundleId: 'com.example.loginMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnvGTChUJe3w3O4UYpKt7wRV6MnHCl_wA',
    appId: '1:688917138939:ios:b89d228b1b12b05d114f5e',
    messagingSenderId: '688917138939',
    projectId: 'metro-auth-20cc7',
    storageBucket: 'metro-auth-20cc7.appspot.com',
    iosBundleId: 'com.example.loginMetro.RunnerTests',
  );
}
